# Generated by Django 4.0.3 on 2022-10-18 18:05

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    Group.objects.bulk_create(
        [Group(name="coach"), Group(name="student"), Group(name="instructor")]
    )
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("question_queue", "0002_alter_user_groups_alter_user_user_permissions"),
    ]

    operations = [migrations.RunPython(create_groups)]
