# Generated by Django 4.0.3 on 2022-10-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_queue', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_access_student_view', 'Can access the student view'), ('can_access_coach_view', 'Can access the coach view'), ('can_access_instructor_view', 'Can access the instructor view'))},
        ),
    ]
