# Generated by Django 4.0.1 on 2022-03-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_queue', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrolledin',
            options={'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'Replies'},
        ),
    ]
