# Generated by Django 4.1.1 on 2022-09-27 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("question_queue", "0003_alter_enrolledin_options_alter_reply_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="QueueQuestion",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="question_queue.question",
                    ),
                ),
                (
                    "answered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("question_queue.question",),
        ),
    ]
