# Generated by Django 4.1.1 on 2022-10-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_queue", "0005_alter_queuequestion_answered_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="queuequestion",
            name="attending",
            field=models.BooleanField(default=False),
        ),
    ]
