# Generated by Django 4.1.2 on 2022-11-08 16:41

from django.db import migrations

SUPPORTED_COURSES = [
    {"course_code": "CS1121", "name": "Intro to Programming 1"},
    {"course_code": "CS1122", "name": "Intro to Programming 2"},
    {"course_code": "CS1131", "name": "Accelerated Intro to Programming"},
    {"course_code": "CS1142", "name": "Programming at HW/SW Interface"},
    {"course_code": "CS2311", "name": "Discrete Structures"},
    {"course_code": "CS2321", "name": "Data Structures"},
    {"course_code": "Other", "name": "Other"},
]


def add_supportedcourses(apps, schema_editor):
    SupportedCourse = apps.get_model("question_queue", "SupportedCourse")

    for course in SUPPORTED_COURSES:
        SupportedCourse.objects.create(**course)


def remove_supportedcourses(apps, schema_editor):
    SupportedCourse = apps.get_model("question_queue", "SupportedCourse")

    for course in SUPPORTED_COURSES:
        SupportedCourse.objects.get(**course).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("question_queue", "0007_supportedcourse_name"),
    ]

    operations = [
        migrations.RunPython(
            code=add_supportedcourses,
            reverse_code=remove_supportedcourses,
            hints={"model_name": "SupportedCourse"},
        )
    ]
