# Generated by Django 4.1.2 on 2022-11-08 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("question_queue", "0008_add_supportedcourses"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterField(
            model_name="assignment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="question_queue.supportedcourse",
            ),
        ),
        migrations.AlterField(
            model_name="enrolledin",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="question_queue.supportedcourse",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="assignment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="question_queue.assignment",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="question_queue.supportedcourse",
            ),
        ),
    ]
